version: '3.9'
services:
  backend:
    container_name: nest-js
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    networks:
      - my-network
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    environment:
      PG_DATA: /var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - ${PG_PORT}:${PG_PORT}
    networks:
      - my-network
    restart: always
networks:
  my-network:
    name: my-network
    driver: bridge
volumes:
  PG_DATA:
