version: '3.9'
services:
  backend:
    container_name: nest-js
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    restart: always
  db:
    container_name: postgres
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    environment:
      PG_DATA: /var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - ${PG_PORT}:${PG_PORT}
    restart: always
