version: '3.9'
services:
  backend:
    container_name: nest-js
    build:
      context: .
      dockerfile: /docker/app/Dockerfile
    ports:
      - "4000:4000"
    restart: always
  db:
    container_name: postgres
    build:
      dockerfile: /docker/db/Dockerfile
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      PG_DATA: /var/lib/postgresql/data